# -*- coding: utf-8 -*-
"""mms_association

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vb70qpm5tzPEyuQ63lsb0s4bM8ycKFvM
"""

!pip install apyori

#LIBRARIES
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

import pandas as pd

df = pd.read_csv("Transaction_ID.csv")

basket = df.groupby(['Transaction_ID'])['Item'].apply(list)
basket = basket.to_frame().reset_index()
basket.head()

te = TransactionEncoder()
data = te.fit(basket['Item']).transform(basket['Item'])
basket_encoded = pd.DataFrame(data, columns=te.columns_)
basket_encoded.head()

freq_items = apriori(basket_encoded, min_support=0.05, use_colnames=True)
freq_items

rules = association_rules(freq_items, metric="confidence", min_threshold=0.5)
rules.sort_values('confidence', ascending=False)

import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

df = pd.read_csv("Transaction_ID.csv")
df.columns = df.columns.str.strip()

models = df['Vehicle'].unique()
results = {}

for m in models:
    print("\n==============================")
    print(f"Processing Vehicle Model: {m}")
    print("==============================")

    temp = df[df['Vehicle'] == m]

    if temp['Transaction_ID'].nunique() < 2:
        print("Not enough transactions for association rules.")
        continue

    baskets = temp.groupby('Transaction_ID')['Item'].apply(list).tolist()

    te = TransactionEncoder()
    te_ary = te.fit(baskets).transform(baskets)
    basket_df = pd.DataFrame(te_ary, columns=te.columns_)

    freq_items = apriori(basket_df, min_support=0.20, use_colnames=True)
    if freq_items.empty:
        print("No frequent itemsets found.")
        continue

    rules = association_rules(freq_items, metric="confidence", min_threshold=0.5)
    if rules.empty:
        print("No association rules for this model.")
        continue

    # ============= CLEAN TABLE (INSIDE LOOP) ============= #
    clean_rules = rules[[
        "antecedents",
        "consequents",
        "antecedent support",
        "consequent support",
        "support",
        "confidence",
        "lift",
        "leverage",
        "conviction"
    ]].sort_values("confidence", ascending=False).reset_index(drop=True)

    results[m] = clean_rules

    print("\nClean Rule Table:")
    print(clean_rules.to_string(index=False))

# END OF LOOP

import pandas as pd
from apyori import apriori

df = pd.read_csv("spare_parts.csv")
df.columns = df.columns.str.strip()
df = df.rename(columns={"Vehicle ": "Vehicle"})  # fix trailing space

vehicles = df['Vehicle'].unique()

results = {}

for v in vehicles:
    print("\n=================================")
    print(f"Processing Vehicle: {v}")
    print("=================================")

    temp = df[df['Vehicle'] == v]

    # If too few transactions → skip
    if temp['Transaction_ID'].nunique() < 2:
        print("Not enough transactions for Apriori.")
        continue

    # Build transaction list
    transactions = temp.groupby('Transaction_ID')['Item'].apply(list).tolist()

    # Run Apriori
    rules = apriori(
        transactions=transactions,
        min_support=0.3,
        min_confidence=0.5,
        min_lift=1.2,
        min_length=2,
        max_length=2
    )

    rules_list = list(rules)

    if len(rules_list) == 0:
        print("No rules found.")
        continue

    # Convert results to DataFrame
    def inspect(results):
        lhs         = [tuple(result.ordered_statistics[0].items_base)[0] for result in results]
        rhs         = [tuple(result.ordered_statistics[0].items_add)[0] for result in results]
        supports    = [result.support for result in results]
        confidences = [result.ordered_statistics[0].confidence for result in results]
        lifts       = [result.ordered_statistics[0].lift for result in results]
        return list(zip(lhs, rhs, supports, confidences, lifts))

    rules_df = pd.DataFrame(inspect(rules_list),
                            columns=['LHS', 'RHS', 'Support', 'Confidence', 'Lift'])

    # Sort by lift (strongest rules first)
    rules_df = rules_df.sort_values("Lift", ascending=False)

    results[v] = rules_df

    print("\nStrong Rules:")
    print(rules_df.to_string(index=False))