/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVehiclesIndexRouteImport } from './routes/_authenticated/vehicles.index'
import { Route as AuthenticatedUserManagementIndexRouteImport } from './routes/_authenticated/user-management.index'
import { Route as AuthenticatedTripTicketsIndexRouteImport } from './routes/_authenticated/trip-tickets.index'
import { Route as AuthenticatedTrackerDevicesIndexRouteImport } from './routes/_authenticated/tracker-devices.index'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedSparePartsIndexRouteImport } from './routes/_authenticated/spare-parts.index'
import { Route as AuthenticatedMaintenanceIndexRouteImport } from './routes/_authenticated/maintenance.index'
import { Route as AuthenticatedJobOrderIndexRouteImport } from './routes/_authenticated/job-order.index'
import { Route as AuthenticatedDriversIndexRouteImport } from './routes/_authenticated/drivers.index'
import { Route as AuthenticatedVehiclesAddVehicleRouteImport } from './routes/_authenticated/vehicles.add-vehicle'
import { Route as AuthenticatedVehiclesVehicleIdRouteImport } from './routes/_authenticated/vehicles.$vehicleId'
import { Route as AuthenticatedUserManagementAddUserRouteImport } from './routes/_authenticated/user-management.add-user'
import { Route as AuthenticatedUserManagementUserIdRouteImport } from './routes/_authenticated/user-management.$userId'
import { Route as AuthenticatedTripTicketsIdRouteImport } from './routes/_authenticated/trip-tickets.$id'
import { Route as AuthenticatedTrackerDevicesAddDeviceRouteImport } from './routes/_authenticated/tracker-devices.add-device'
import { Route as AuthenticatedTrackerDevicesDeviceIdRouteImport } from './routes/_authenticated/tracker-devices.$deviceId'
import { Route as AuthenticatedToolsAddToolsRouteImport } from './routes/_authenticated/tools.add-tools'
import { Route as AuthenticatedToolsToolsIdRouteImport } from './routes/_authenticated/tools.$toolsId'
import { Route as AuthenticatedSparePartsAddSparePartRouteImport } from './routes/_authenticated/spare-parts.add-spare-part'
import { Route as AuthenticatedSparePartsSparePartIdRouteImport } from './routes/_authenticated/spare-parts.$sparePartId'
import { Route as AuthenticatedMaintenanceAddMaintenanceRouteImport } from './routes/_authenticated/maintenance.add-maintenance'
import { Route as AuthenticatedMaintenanceIdRouteImport } from './routes/_authenticated/maintenance.$id'
import { Route as AuthenticatedJobOrderIdRouteImport } from './routes/_authenticated/job-order.$id'
import { Route as AuthenticatedDriversIdRouteImport } from './routes/_authenticated/drivers.$id'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVehiclesIndexRoute =
  AuthenticatedVehiclesIndexRouteImport.update({
    id: '/vehicles/',
    path: '/vehicles/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserManagementIndexRoute =
  AuthenticatedUserManagementIndexRouteImport.update({
    id: '/user-management/',
    path: '/user-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripTicketsIndexRoute =
  AuthenticatedTripTicketsIndexRouteImport.update({
    id: '/trip-tickets/',
    path: '/trip-tickets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackerDevicesIndexRoute =
  AuthenticatedTrackerDevicesIndexRouteImport.update({
    id: '/tracker-devices/',
    path: '/tracker-devices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSparePartsIndexRoute =
  AuthenticatedSparePartsIndexRouteImport.update({
    id: '/spare-parts/',
    path: '/spare-parts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceIndexRoute =
  AuthenticatedMaintenanceIndexRouteImport.update({
    id: '/maintenance/',
    path: '/maintenance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobOrderIndexRoute =
  AuthenticatedJobOrderIndexRouteImport.update({
    id: '/job-order/',
    path: '/job-order/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDriversIndexRoute =
  AuthenticatedDriversIndexRouteImport.update({
    id: '/drivers/',
    path: '/drivers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVehiclesAddVehicleRoute =
  AuthenticatedVehiclesAddVehicleRouteImport.update({
    id: '/vehicles/add-vehicle',
    path: '/vehicles/add-vehicle',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVehiclesVehicleIdRoute =
  AuthenticatedVehiclesVehicleIdRouteImport.update({
    id: '/vehicles/$vehicleId',
    path: '/vehicles/$vehicleId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserManagementAddUserRoute =
  AuthenticatedUserManagementAddUserRouteImport.update({
    id: '/user-management/add-user',
    path: '/user-management/add-user',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUserManagementUserIdRoute =
  AuthenticatedUserManagementUserIdRouteImport.update({
    id: '/user-management/$userId',
    path: '/user-management/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTripTicketsIdRoute =
  AuthenticatedTripTicketsIdRouteImport.update({
    id: '/trip-tickets/$id',
    path: '/trip-tickets/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackerDevicesAddDeviceRoute =
  AuthenticatedTrackerDevicesAddDeviceRouteImport.update({
    id: '/tracker-devices/add-device',
    path: '/tracker-devices/add-device',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrackerDevicesDeviceIdRoute =
  AuthenticatedTrackerDevicesDeviceIdRouteImport.update({
    id: '/tracker-devices/$deviceId',
    path: '/tracker-devices/$deviceId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsAddToolsRoute =
  AuthenticatedToolsAddToolsRouteImport.update({
    id: '/tools/add-tools',
    path: '/tools/add-tools',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedToolsToolsIdRoute =
  AuthenticatedToolsToolsIdRouteImport.update({
    id: '/tools/$toolsId',
    path: '/tools/$toolsId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSparePartsAddSparePartRoute =
  AuthenticatedSparePartsAddSparePartRouteImport.update({
    id: '/spare-parts/add-spare-part',
    path: '/spare-parts/add-spare-part',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSparePartsSparePartIdRoute =
  AuthenticatedSparePartsSparePartIdRouteImport.update({
    id: '/spare-parts/$sparePartId',
    path: '/spare-parts/$sparePartId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceAddMaintenanceRoute =
  AuthenticatedMaintenanceAddMaintenanceRouteImport.update({
    id: '/maintenance/add-maintenance',
    path: '/maintenance/add-maintenance',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMaintenanceIdRoute =
  AuthenticatedMaintenanceIdRouteImport.update({
    id: '/maintenance/$id',
    path: '/maintenance/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJobOrderIdRoute = AuthenticatedJobOrderIdRouteImport.update({
  id: '/job-order/$id',
  path: '/job-order/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDriversIdRoute = AuthenticatedDriversIdRouteImport.update({
  id: '/drivers/$id',
  path: '/drivers/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof PublicLoginRoute
  '/drivers/$id': typeof AuthenticatedDriversIdRoute
  '/job-order/$id': typeof AuthenticatedJobOrderIdRoute
  '/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/maintenance/add-maintenance': typeof AuthenticatedMaintenanceAddMaintenanceRoute
  '/spare-parts/$sparePartId': typeof AuthenticatedSparePartsSparePartIdRoute
  '/spare-parts/add-spare-part': typeof AuthenticatedSparePartsAddSparePartRoute
  '/tools/$toolsId': typeof AuthenticatedToolsToolsIdRoute
  '/tools/add-tools': typeof AuthenticatedToolsAddToolsRoute
  '/tracker-devices/$deviceId': typeof AuthenticatedTrackerDevicesDeviceIdRoute
  '/tracker-devices/add-device': typeof AuthenticatedTrackerDevicesAddDeviceRoute
  '/trip-tickets/$id': typeof AuthenticatedTripTicketsIdRoute
  '/user-management/$userId': typeof AuthenticatedUserManagementUserIdRoute
  '/user-management/add-user': typeof AuthenticatedUserManagementAddUserRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/vehicles/add-vehicle': typeof AuthenticatedVehiclesAddVehicleRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/job-order': typeof AuthenticatedJobOrderIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/spare-parts': typeof AuthenticatedSparePartsIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/tracker-devices': typeof AuthenticatedTrackerDevicesIndexRoute
  '/trip-tickets': typeof AuthenticatedTripTicketsIndexRoute
  '/user-management': typeof AuthenticatedUserManagementIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/organization': typeof AuthenticatedOrganizationRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login': typeof PublicLoginRoute
  '/drivers/$id': typeof AuthenticatedDriversIdRoute
  '/job-order/$id': typeof AuthenticatedJobOrderIdRoute
  '/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/maintenance/add-maintenance': typeof AuthenticatedMaintenanceAddMaintenanceRoute
  '/spare-parts/$sparePartId': typeof AuthenticatedSparePartsSparePartIdRoute
  '/spare-parts/add-spare-part': typeof AuthenticatedSparePartsAddSparePartRoute
  '/tools/$toolsId': typeof AuthenticatedToolsToolsIdRoute
  '/tools/add-tools': typeof AuthenticatedToolsAddToolsRoute
  '/tracker-devices/$deviceId': typeof AuthenticatedTrackerDevicesDeviceIdRoute
  '/tracker-devices/add-device': typeof AuthenticatedTrackerDevicesAddDeviceRoute
  '/trip-tickets/$id': typeof AuthenticatedTripTicketsIdRoute
  '/user-management/$userId': typeof AuthenticatedUserManagementUserIdRoute
  '/user-management/add-user': typeof AuthenticatedUserManagementAddUserRoute
  '/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/vehicles/add-vehicle': typeof AuthenticatedVehiclesAddVehicleRoute
  '/drivers': typeof AuthenticatedDriversIndexRoute
  '/job-order': typeof AuthenticatedJobOrderIndexRoute
  '/maintenance': typeof AuthenticatedMaintenanceIndexRoute
  '/spare-parts': typeof AuthenticatedSparePartsIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/tracker-devices': typeof AuthenticatedTrackerDevicesIndexRoute
  '/trip-tickets': typeof AuthenticatedTripTicketsIndexRoute
  '/user-management': typeof AuthenticatedUserManagementIndexRoute
  '/vehicles': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authenticated/drivers/$id': typeof AuthenticatedDriversIdRoute
  '/_authenticated/job-order/$id': typeof AuthenticatedJobOrderIdRoute
  '/_authenticated/maintenance/$id': typeof AuthenticatedMaintenanceIdRoute
  '/_authenticated/maintenance/add-maintenance': typeof AuthenticatedMaintenanceAddMaintenanceRoute
  '/_authenticated/spare-parts/$sparePartId': typeof AuthenticatedSparePartsSparePartIdRoute
  '/_authenticated/spare-parts/add-spare-part': typeof AuthenticatedSparePartsAddSparePartRoute
  '/_authenticated/tools/$toolsId': typeof AuthenticatedToolsToolsIdRoute
  '/_authenticated/tools/add-tools': typeof AuthenticatedToolsAddToolsRoute
  '/_authenticated/tracker-devices/$deviceId': typeof AuthenticatedTrackerDevicesDeviceIdRoute
  '/_authenticated/tracker-devices/add-device': typeof AuthenticatedTrackerDevicesAddDeviceRoute
  '/_authenticated/trip-tickets/$id': typeof AuthenticatedTripTicketsIdRoute
  '/_authenticated/user-management/$userId': typeof AuthenticatedUserManagementUserIdRoute
  '/_authenticated/user-management/add-user': typeof AuthenticatedUserManagementAddUserRoute
  '/_authenticated/vehicles/$vehicleId': typeof AuthenticatedVehiclesVehicleIdRoute
  '/_authenticated/vehicles/add-vehicle': typeof AuthenticatedVehiclesAddVehicleRoute
  '/_authenticated/drivers/': typeof AuthenticatedDriversIndexRoute
  '/_authenticated/job-order/': typeof AuthenticatedJobOrderIndexRoute
  '/_authenticated/maintenance/': typeof AuthenticatedMaintenanceIndexRoute
  '/_authenticated/spare-parts/': typeof AuthenticatedSparePartsIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/tracker-devices/': typeof AuthenticatedTrackerDevicesIndexRoute
  '/_authenticated/trip-tickets/': typeof AuthenticatedTripTicketsIndexRoute
  '/_authenticated/user-management/': typeof AuthenticatedUserManagementIndexRoute
  '/_authenticated/vehicles/': typeof AuthenticatedVehiclesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/organization'
    | '/profile'
    | '/login'
    | '/drivers/$id'
    | '/job-order/$id'
    | '/maintenance/$id'
    | '/maintenance/add-maintenance'
    | '/spare-parts/$sparePartId'
    | '/spare-parts/add-spare-part'
    | '/tools/$toolsId'
    | '/tools/add-tools'
    | '/tracker-devices/$deviceId'
    | '/tracker-devices/add-device'
    | '/trip-tickets/$id'
    | '/user-management/$userId'
    | '/user-management/add-user'
    | '/vehicles/$vehicleId'
    | '/vehicles/add-vehicle'
    | '/drivers'
    | '/job-order'
    | '/maintenance'
    | '/spare-parts'
    | '/tools'
    | '/tracker-devices'
    | '/trip-tickets'
    | '/user-management'
    | '/vehicles'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/organization'
    | '/profile'
    | '/login'
    | '/drivers/$id'
    | '/job-order/$id'
    | '/maintenance/$id'
    | '/maintenance/add-maintenance'
    | '/spare-parts/$sparePartId'
    | '/spare-parts/add-spare-part'
    | '/tools/$toolsId'
    | '/tools/add-tools'
    | '/tracker-devices/$deviceId'
    | '/tracker-devices/add-device'
    | '/trip-tickets/$id'
    | '/user-management/$userId'
    | '/user-management/add-user'
    | '/vehicles/$vehicleId'
    | '/vehicles/add-vehicle'
    | '/drivers'
    | '/job-order'
    | '/maintenance'
    | '/spare-parts'
    | '/tools'
    | '/tracker-devices'
    | '/trip-tickets'
    | '/user-management'
    | '/vehicles'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard'
    | '/_authenticated/organization'
    | '/_authenticated/profile'
    | '/_public/login'
    | '/_authenticated/drivers/$id'
    | '/_authenticated/job-order/$id'
    | '/_authenticated/maintenance/$id'
    | '/_authenticated/maintenance/add-maintenance'
    | '/_authenticated/spare-parts/$sparePartId'
    | '/_authenticated/spare-parts/add-spare-part'
    | '/_authenticated/tools/$toolsId'
    | '/_authenticated/tools/add-tools'
    | '/_authenticated/tracker-devices/$deviceId'
    | '/_authenticated/tracker-devices/add-device'
    | '/_authenticated/trip-tickets/$id'
    | '/_authenticated/user-management/$userId'
    | '/_authenticated/user-management/add-user'
    | '/_authenticated/vehicles/$vehicleId'
    | '/_authenticated/vehicles/add-vehicle'
    | '/_authenticated/drivers/'
    | '/_authenticated/job-order/'
    | '/_authenticated/maintenance/'
    | '/_authenticated/spare-parts/'
    | '/_authenticated/tools/'
    | '/_authenticated/tracker-devices/'
    | '/_authenticated/trip-tickets/'
    | '/_authenticated/user-management/'
    | '/_authenticated/vehicles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organization': {
      id: '/_authenticated/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/': {
      id: '/_authenticated/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof AuthenticatedVehiclesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-management/': {
      id: '/_authenticated/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trip-tickets/': {
      id: '/_authenticated/trip-tickets/'
      path: '/trip-tickets'
      fullPath: '/trip-tickets'
      preLoaderRoute: typeof AuthenticatedTripTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker-devices/': {
      id: '/_authenticated/tracker-devices/'
      path: '/tracker-devices'
      fullPath: '/tracker-devices'
      preLoaderRoute: typeof AuthenticatedTrackerDevicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spare-parts/': {
      id: '/_authenticated/spare-parts/'
      path: '/spare-parts'
      fullPath: '/spare-parts'
      preLoaderRoute: typeof AuthenticatedSparePartsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/': {
      id: '/_authenticated/maintenance/'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/job-order/': {
      id: '/_authenticated/job-order/'
      path: '/job-order'
      fullPath: '/job-order'
      preLoaderRoute: typeof AuthenticatedJobOrderIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers/': {
      id: '/_authenticated/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof AuthenticatedDriversIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/add-vehicle': {
      id: '/_authenticated/vehicles/add-vehicle'
      path: '/vehicles/add-vehicle'
      fullPath: '/vehicles/add-vehicle'
      preLoaderRoute: typeof AuthenticatedVehiclesAddVehicleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vehicles/$vehicleId': {
      id: '/_authenticated/vehicles/$vehicleId'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId'
      preLoaderRoute: typeof AuthenticatedVehiclesVehicleIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-management/add-user': {
      id: '/_authenticated/user-management/add-user'
      path: '/user-management/add-user'
      fullPath: '/user-management/add-user'
      preLoaderRoute: typeof AuthenticatedUserManagementAddUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-management/$userId': {
      id: '/_authenticated/user-management/$userId'
      path: '/user-management/$userId'
      fullPath: '/user-management/$userId'
      preLoaderRoute: typeof AuthenticatedUserManagementUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trip-tickets/$id': {
      id: '/_authenticated/trip-tickets/$id'
      path: '/trip-tickets/$id'
      fullPath: '/trip-tickets/$id'
      preLoaderRoute: typeof AuthenticatedTripTicketsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker-devices/add-device': {
      id: '/_authenticated/tracker-devices/add-device'
      path: '/tracker-devices/add-device'
      fullPath: '/tracker-devices/add-device'
      preLoaderRoute: typeof AuthenticatedTrackerDevicesAddDeviceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tracker-devices/$deviceId': {
      id: '/_authenticated/tracker-devices/$deviceId'
      path: '/tracker-devices/$deviceId'
      fullPath: '/tracker-devices/$deviceId'
      preLoaderRoute: typeof AuthenticatedTrackerDevicesDeviceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/add-tools': {
      id: '/_authenticated/tools/add-tools'
      path: '/tools/add-tools'
      fullPath: '/tools/add-tools'
      preLoaderRoute: typeof AuthenticatedToolsAddToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tools/$toolsId': {
      id: '/_authenticated/tools/$toolsId'
      path: '/tools/$toolsId'
      fullPath: '/tools/$toolsId'
      preLoaderRoute: typeof AuthenticatedToolsToolsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spare-parts/add-spare-part': {
      id: '/_authenticated/spare-parts/add-spare-part'
      path: '/spare-parts/add-spare-part'
      fullPath: '/spare-parts/add-spare-part'
      preLoaderRoute: typeof AuthenticatedSparePartsAddSparePartRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/spare-parts/$sparePartId': {
      id: '/_authenticated/spare-parts/$sparePartId'
      path: '/spare-parts/$sparePartId'
      fullPath: '/spare-parts/$sparePartId'
      preLoaderRoute: typeof AuthenticatedSparePartsSparePartIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/add-maintenance': {
      id: '/_authenticated/maintenance/add-maintenance'
      path: '/maintenance/add-maintenance'
      fullPath: '/maintenance/add-maintenance'
      preLoaderRoute: typeof AuthenticatedMaintenanceAddMaintenanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/maintenance/$id': {
      id: '/_authenticated/maintenance/$id'
      path: '/maintenance/$id'
      fullPath: '/maintenance/$id'
      preLoaderRoute: typeof AuthenticatedMaintenanceIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/job-order/$id': {
      id: '/_authenticated/job-order/$id'
      path: '/job-order/$id'
      fullPath: '/job-order/$id'
      preLoaderRoute: typeof AuthenticatedJobOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drivers/$id': {
      id: '/_authenticated/drivers/$id'
      path: '/drivers/$id'
      fullPath: '/drivers/$id'
      preLoaderRoute: typeof AuthenticatedDriversIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDriversIdRoute: typeof AuthenticatedDriversIdRoute
  AuthenticatedJobOrderIdRoute: typeof AuthenticatedJobOrderIdRoute
  AuthenticatedMaintenanceIdRoute: typeof AuthenticatedMaintenanceIdRoute
  AuthenticatedMaintenanceAddMaintenanceRoute: typeof AuthenticatedMaintenanceAddMaintenanceRoute
  AuthenticatedSparePartsSparePartIdRoute: typeof AuthenticatedSparePartsSparePartIdRoute
  AuthenticatedSparePartsAddSparePartRoute: typeof AuthenticatedSparePartsAddSparePartRoute
  AuthenticatedToolsToolsIdRoute: typeof AuthenticatedToolsToolsIdRoute
  AuthenticatedToolsAddToolsRoute: typeof AuthenticatedToolsAddToolsRoute
  AuthenticatedTrackerDevicesDeviceIdRoute: typeof AuthenticatedTrackerDevicesDeviceIdRoute
  AuthenticatedTrackerDevicesAddDeviceRoute: typeof AuthenticatedTrackerDevicesAddDeviceRoute
  AuthenticatedTripTicketsIdRoute: typeof AuthenticatedTripTicketsIdRoute
  AuthenticatedUserManagementUserIdRoute: typeof AuthenticatedUserManagementUserIdRoute
  AuthenticatedUserManagementAddUserRoute: typeof AuthenticatedUserManagementAddUserRoute
  AuthenticatedVehiclesVehicleIdRoute: typeof AuthenticatedVehiclesVehicleIdRoute
  AuthenticatedVehiclesAddVehicleRoute: typeof AuthenticatedVehiclesAddVehicleRoute
  AuthenticatedDriversIndexRoute: typeof AuthenticatedDriversIndexRoute
  AuthenticatedJobOrderIndexRoute: typeof AuthenticatedJobOrderIndexRoute
  AuthenticatedMaintenanceIndexRoute: typeof AuthenticatedMaintenanceIndexRoute
  AuthenticatedSparePartsIndexRoute: typeof AuthenticatedSparePartsIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedTrackerDevicesIndexRoute: typeof AuthenticatedTrackerDevicesIndexRoute
  AuthenticatedTripTicketsIndexRoute: typeof AuthenticatedTripTicketsIndexRoute
  AuthenticatedUserManagementIndexRoute: typeof AuthenticatedUserManagementIndexRoute
  AuthenticatedVehiclesIndexRoute: typeof AuthenticatedVehiclesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDriversIdRoute: AuthenticatedDriversIdRoute,
  AuthenticatedJobOrderIdRoute: AuthenticatedJobOrderIdRoute,
  AuthenticatedMaintenanceIdRoute: AuthenticatedMaintenanceIdRoute,
  AuthenticatedMaintenanceAddMaintenanceRoute:
    AuthenticatedMaintenanceAddMaintenanceRoute,
  AuthenticatedSparePartsSparePartIdRoute:
    AuthenticatedSparePartsSparePartIdRoute,
  AuthenticatedSparePartsAddSparePartRoute:
    AuthenticatedSparePartsAddSparePartRoute,
  AuthenticatedToolsToolsIdRoute: AuthenticatedToolsToolsIdRoute,
  AuthenticatedToolsAddToolsRoute: AuthenticatedToolsAddToolsRoute,
  AuthenticatedTrackerDevicesDeviceIdRoute:
    AuthenticatedTrackerDevicesDeviceIdRoute,
  AuthenticatedTrackerDevicesAddDeviceRoute:
    AuthenticatedTrackerDevicesAddDeviceRoute,
  AuthenticatedTripTicketsIdRoute: AuthenticatedTripTicketsIdRoute,
  AuthenticatedUserManagementUserIdRoute:
    AuthenticatedUserManagementUserIdRoute,
  AuthenticatedUserManagementAddUserRoute:
    AuthenticatedUserManagementAddUserRoute,
  AuthenticatedVehiclesVehicleIdRoute: AuthenticatedVehiclesVehicleIdRoute,
  AuthenticatedVehiclesAddVehicleRoute: AuthenticatedVehiclesAddVehicleRoute,
  AuthenticatedDriversIndexRoute: AuthenticatedDriversIndexRoute,
  AuthenticatedJobOrderIndexRoute: AuthenticatedJobOrderIndexRoute,
  AuthenticatedMaintenanceIndexRoute: AuthenticatedMaintenanceIndexRoute,
  AuthenticatedSparePartsIndexRoute: AuthenticatedSparePartsIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedTrackerDevicesIndexRoute: AuthenticatedTrackerDevicesIndexRoute,
  AuthenticatedTripTicketsIndexRoute: AuthenticatedTripTicketsIndexRoute,
  AuthenticatedUserManagementIndexRoute: AuthenticatedUserManagementIndexRoute,
  AuthenticatedVehiclesIndexRoute: AuthenticatedVehiclesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
