# -*- coding: utf-8 -*-
"""mms_randomfiorest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15SRuS7OnwWKq-ooaYZYtj1LbduTJHcPs
"""

# ======================================================
# RANDOM FOREST – FINAL VERSION
# ======================================================

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)
from imblearn.over_sampling import SMOTE

# ------------------------------------------------------
# 1. LOAD DATA
# ------------------------------------------------------
df = pd.read_csv("final_datasets_CLEAN.csv")

# ------------------------------------------------------
# 2. DATE HANDLING
# ------------------------------------------------------
df["DATE"] = pd.to_datetime(df["DATE"], errors="coerce")
df = df.dropna(subset=["DATE"])

# ------------------------------------------------------
# 3. FEATURE SELECTION (SAFE FEATURES ONLY)
# ------------------------------------------------------
features = [
    "KM_SINCE_LAST_MAINT",
    "AVG_DAILY_KM",
    "MAINT_FREQ_12M"
]

X = df[features].fillna(0)
y = df["Failure_flag"]

# ------------------------------------------------------
# 4. STRATIFIED TRAIN–TEST SPLIT (CRITICAL FIX)
# ------------------------------------------------------
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.25,
    random_state=42,
    stratify=y
)

print("Train class distribution:\n", y_train.value_counts())
print("Test class distribution:\n", y_test.value_counts())

# ------------------------------------------------------
# 5. SMOTE (TRAINING DATA ONLY)
# ------------------------------------------------------
smote = SMOTE(random_state=42)
X_train_res, y_train_res = smote.fit_resample(X_train, y_train)

# ------------------------------------------------------
# 6. RANDOM FOREST MODEL
# ------------------------------------------------------
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf.fit(X_train_res, y_train_res)

# ------------------------------------------------------
# 7. PREDICTION
# ------------------------------------------------------
y_pred = rf.predict(X_test)
y_prob = rf.predict_proba(X_test)[:, 1]

# ------------------------------------------------------
# 8. CONFUSION MATRIX (FORCED 2×2)
# ------------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])
tn, fp, fn, tp = cm.ravel()

# ------------------------------------------------------
# 9. METRICS
# ------------------------------------------------------
tpr = tp / (tp + fn) if (tp + fn) > 0 else 0
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
f1 = f1_score(y_test, y_pred, zero_division=0)
roc_auc = roc_auc_score(y_test, y_prob)

# ------------------------------------------------------
# 10. OUTPUT
# ------------------------------------------------------
print("\nRANDOM FOREST RESULTS")
print("Confusion Matrix:")
print(cm)
print(f"True Positive Rate (Recall): {tpr:.4f}")
print(f"Precision: {precision:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"ROC–AUC: {roc_auc:.4f}")