/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as ReportsIndexRouteImport } from './routes/reports/index'
import { Route as MaintenanceScheduleIndexRouteImport } from './routes/maintenance-schedule/index'
import { Route as JobOrderIndexRouteImport } from './routes/job-order/index'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceScheduleIndexRoute =
  MaintenanceScheduleIndexRouteImport.update({
    id: '/maintenance-schedule/',
    path: '/maintenance-schedule/',
    getParentRoute: () => rootRouteImport,
  } as any)
const JobOrderIndexRoute = JobOrderIndexRouteImport.update({
  id: '/job-order/',
  path: '/job-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/job-order': typeof JobOrderIndexRoute
  '/maintenance-schedule': typeof MaintenanceScheduleIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reservations': typeof ReservationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/job-order': typeof JobOrderIndexRoute
  '/maintenance-schedule': typeof MaintenanceScheduleIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reservations': typeof ReservationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/job-order/': typeof JobOrderIndexRoute
  '/maintenance-schedule/': typeof MaintenanceScheduleIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/drivers'
    | '/job-order'
    | '/maintenance-schedule'
    | '/reports'
    | '/reservations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/drivers'
    | '/job-order'
    | '/maintenance-schedule'
    | '/reports'
    | '/reservations'
  id:
    | '__root__'
    | '/'
    | '/assets/'
    | '/dashboard/'
    | '/drivers/'
    | '/job-order/'
    | '/maintenance-schedule/'
    | '/reports/'
    | '/reservations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  JobOrderIndexRoute: typeof JobOrderIndexRoute
  MaintenanceScheduleIndexRoute: typeof MaintenanceScheduleIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-schedule/': {
      id: '/maintenance-schedule/'
      path: '/maintenance-schedule'
      fullPath: '/maintenance-schedule'
      preLoaderRoute: typeof MaintenanceScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-order/': {
      id: '/job-order/'
      path: '/job-order'
      fullPath: '/job-order'
      preLoaderRoute: typeof JobOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  JobOrderIndexRoute: JobOrderIndexRoute,
  MaintenanceScheduleIndexRoute: MaintenanceScheduleIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
