/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserManagementIndexRouteImport } from './routes/user-management/index'
import { Route as ReservationsIndexRouteImport } from './routes/reservations/index'
import { Route as MaintenanceScheduleIndexRouteImport } from './routes/maintenance-schedule/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as JobOrderIndexRouteImport } from './routes/job-order/index'
import { Route as DriversIndexRouteImport } from './routes/drivers/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AssetsIndexRouteImport } from './routes/assets/index'
import { Route as UserManagementAddUserIndexRouteImport } from './routes/user-management/add-user/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsIndexRoute = ReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceScheduleIndexRoute =
  MaintenanceScheduleIndexRouteImport.update({
    id: '/maintenance-schedule/',
    path: '/maintenance-schedule/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobOrderIndexRoute = JobOrderIndexRouteImport.update({
  id: '/job-order/',
  path: '/job-order/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversIndexRoute = DriversIndexRouteImport.update({
  id: '/drivers/',
  path: '/drivers/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsIndexRoute = AssetsIndexRouteImport.update({
  id: '/assets/',
  path: '/assets/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementAddUserIndexRoute =
  UserManagementAddUserIndexRouteImport.update({
    id: '/user-management/add-user/',
    path: '/user-management/add-user/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/job-order': typeof JobOrderIndexRoute
  '/login': typeof LoginIndexRoute
  '/maintenance-schedule': typeof MaintenanceScheduleIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/user-management': typeof UserManagementIndexRoute
  '/user-management/add-user': typeof UserManagementAddUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/drivers': typeof DriversIndexRoute
  '/job-order': typeof JobOrderIndexRoute
  '/login': typeof LoginIndexRoute
  '/maintenance-schedule': typeof MaintenanceScheduleIndexRoute
  '/reservations': typeof ReservationsIndexRoute
  '/user-management': typeof UserManagementIndexRoute
  '/user-management/add-user': typeof UserManagementAddUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets/': typeof AssetsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/drivers/': typeof DriversIndexRoute
  '/job-order/': typeof JobOrderIndexRoute
  '/login/': typeof LoginIndexRoute
  '/maintenance-schedule/': typeof MaintenanceScheduleIndexRoute
  '/reservations/': typeof ReservationsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/user-management/add-user/': typeof UserManagementAddUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/drivers'
    | '/job-order'
    | '/login'
    | '/maintenance-schedule'
    | '/reservations'
    | '/user-management'
    | '/user-management/add-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/dashboard'
    | '/drivers'
    | '/job-order'
    | '/login'
    | '/maintenance-schedule'
    | '/reservations'
    | '/user-management'
    | '/user-management/add-user'
  id:
    | '__root__'
    | '/'
    | '/assets/'
    | '/dashboard/'
    | '/drivers/'
    | '/job-order/'
    | '/login/'
    | '/maintenance-schedule/'
    | '/reservations/'
    | '/user-management/'
    | '/user-management/add-user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsIndexRoute: typeof AssetsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DriversIndexRoute: typeof DriversIndexRoute
  JobOrderIndexRoute: typeof JobOrderIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  MaintenanceScheduleIndexRoute: typeof MaintenanceScheduleIndexRoute
  ReservationsIndexRoute: typeof ReservationsIndexRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
  UserManagementAddUserIndexRoute: typeof UserManagementAddUserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations/': {
      id: '/reservations/'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance-schedule/': {
      id: '/maintenance-schedule/'
      path: '/maintenance-schedule'
      fullPath: '/maintenance-schedule'
      preLoaderRoute: typeof MaintenanceScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-order/': {
      id: '/job-order/'
      path: '/job-order'
      fullPath: '/job-order'
      preLoaderRoute: typeof JobOrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers/': {
      id: '/drivers/'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/': {
      id: '/assets/'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/add-user/': {
      id: '/user-management/add-user/'
      path: '/user-management/add-user'
      fullPath: '/user-management/add-user'
      preLoaderRoute: typeof UserManagementAddUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsIndexRoute: AssetsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DriversIndexRoute: DriversIndexRoute,
  JobOrderIndexRoute: JobOrderIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  MaintenanceScheduleIndexRoute: MaintenanceScheduleIndexRoute,
  ReservationsIndexRoute: ReservationsIndexRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
  UserManagementAddUserIndexRoute: UserManagementAddUserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
